[features]
seeds = false
skip-lint = false
[programs.localnet]
metaticket_vault_escrow_program_v1 = "3NGfXZScUbEa57UNnSU95qM7Pu72DwsvHUPo7ca1rxvc"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/lonestardev/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
