[features]
seeds = true
skip-lint = false
[programs.devnet]
metaticket_vault_escrow_program_v1 = "3NGfXZScUbEa57UNnSU95qM7Pu72DwsvHUPo7ca1rxvc"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/lonestardev/my-solana-wallet/metaticket.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

